# eg from https://www.tutorialspoint.com/docker/docker_file.htm
FROM ubuntu:latest  
##FROM ubuntu:trusty  ## nope, something strange with bofh!!
MAINTAINER tin(at)berkeley.edu
RUN apt-get update && apt-get install -y nginx
CMD ["echo","image created"]
