version: '2'
services:
  app:
    image: my-first-container-app
    environment: 
      - WHO=elvis
  web:
    image: my-first-container-nginx
    ports:
    - "80:8080"
    volumes:
    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
